In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
calender = pd.read_csv("G:\\data analysis\\final project\\Calendar.csv")
calender

            Date Start of Year Start of Quarter Start of Month
0     2012-01-01    2012-01-01       2012-01-01     2012-01-01
1     2012-01-02    2012-01-01       2012-01-01     2012-01-01
2     2012-01-03    2012-01-01       2012-01-01     2012-01-01
3     2012-01-04    2012-01-01       2012-01-01     2012-01-01
4     2012-01-05    2012-01-01       2012-01-01     2012-01-01
...          ...           ...              ...            ...
2552  2018-12-27    2018-01-01       2018-10-01     2018-12-01
2553  2018-12-28    2018-01-01       2018-10-01     2018-12-01
2554  2018-12-29    2018-01-01       2018-10-01     2018-12-01
2555  2018-12-30    2018-01-01       2018-10-01     2018-12-01
2556  2018-12-31    2018-01-01       2018-10-01     2018-12-01

[2557 rows x 4 columns]

In [3]:
calender.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2557 entries, 0 to 2556
Data columns (total 4 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Date              2557 non-null   object
 1   Start of Year     2557 non-null   object
 2   Start of Quarter  2557 non-null   object
 3   Start of Month    2557 non-null   object
dtypes: object(4)
memory usage: 80.0+ KB

In [4]:
calender.isnull().sum()

Date                0
Start of Year       0
Start of Quarter    0
Start of Month      0
dtype: int64

In [5]:
calender.duplicated().sum()

np.int64(0)

In [6]:
calender['Date']= pd.to_datetime(calender['Date'])
calender['Start of Year']= pd.to_datetime(calender['Start of Year'])
calender['Start of Quarter']= pd.to_datetime(calender['Start of Quarter'])
calender['Start of Month']= pd.to_datetime(calender['Start of Month'])

In [7]:
calender.to_csv("Calendar.csv", index=False)

In [7]:
calender.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2557 entries, 0 to 2556
Data columns (total 4 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Date              2557 non-null   datetime64[ns]
 1   Start of Year     2557 non-null   datetime64[ns]
 2   Start of Quarter  2557 non-null   datetime64[ns]
 3   Start of Month    2557 non-null   datetime64[ns]
dtypes: datetime64[ns](4)
memory usage: 80.0 KB

In [8]:
activity = pd.read_csv("G:\\data analysis\\final project\\Customer Flight Activity.csv")
activity

,Loyalty Number,Year,Month,Total Flights,Distance,Points Accumulated,Points Redeemed,Dollar Cost Points Redeemed
0,100590,2018,6,12,15276,22914.0,0,0
1,100590,2018,7,12,9168,13752.0,0,0
2,100590,2018,5,4,6504,9756.0,0,0
3,100590,2018,10,0,0,0.0,512,92
4,100590,2018,2,0,0,0.0,0,0
...,...,...,...,...,...,...,...,...
392931,999986,2018,4,0,0,0.0,0,0
392932,999986,2018,5,0,0,0.0,0,0
392933,999986,2018,6,0,0,0.0,0,0
392934,999986,2018,9,0,0,0.0,0,0
392935,999986,2018,12,0,0,0.0,0,0

In [9]:
activity.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 392936 entries, 0 to 392935
Data columns (total 8 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   Loyalty Number               392936 non-null  int64
 1   Year                         392936 non-null  int64
 2   Month                        392936 non-null  int64
 3   Total Flights                392936 non-null  int64
 4   Distance                     392936 non-null  int64
 5   Points Accumulated           392936 non-null  float64
 6   Points Redeemed              392936 non-null  int64
 7   Dollar Cost Points Redeemed  392936 non-null  int64
dtypes: float64(1), int64(7)
memory usage: 24.0 MB

In [10]:
activity.isnull().sum()

Loyalty Number                 0
Year                           0
Month                          0
Total Flights                  0
Distance                       0
Points Accumulated             0
Points Redeemed                0
Dollar Cost Points Redeemed    0
dtype: int64

In [11]:
activity.duplicated().sum()

np.int64(1922)

In [12]:
activity[activity.duplicated()]

,Loyalty Number,Year,Month,Total Flights,Distance,Points Accumulated,Points Redeemed,Dollar Cost Points Redeemed
176809,357901,2018,2,0,0,0.0,0,0
176811,357901,2018,3,0,0,0.0,0,0
176813,357901,2018,4,0,0,0.0,0,0
176819,357901,2018,9,0,0,0.0,0,0
176822,357901,2018,11,0,0,0.0,0,0
...,...,...,...,...,...,...,...,...
389816,732304,2018,3,0,0,0.0,0,0
389818,732304,2018,4,0,0,0.0,0,0
392342,951353,2018,2,0,0,0.0,0,0
392344,951353,2018,3,0,0,0.0,0,0
392347,951353,2018,5,0,0,0.0,0,0

In [13]:
activity.drop_duplicates()

,Loyalty Number,Year,Month,Total Flights,Distance,Points Accumulated,Points Redeemed,Dollar Cost Points Redeemed
0,100590,2018,6,12,15276,22914.0,0,0
1,100590,2018,7,12,9168,13752.0,0,0
2,100590,2018,5,4,6504,9756.0,0,0
3,100590,2018,10,0,0,0.0,512,92
4,100590,2018,2,0,0,0.0,0,0
...,...,...,...,...,...,...,...,...
392931,999986,2018,4,0,0,0.0,0,0
392932,999986,2018,5,0,0,0.0,0,0
392933,999986,2018,6,0,0,0.0,0,0
392934,999986,2018,9,0,0,0.0,0,0
392935,999986,2018,12,0,0,0.0,0,0

In [14]:
columns = [
    "Total Flights",
    "Distance",
    "Points Accumulated",
    
]
activity =activity [activity[columns].apply(lambda row: not all(row ==0),axis=1)]

In [15]:
activity

,Loyalty Number,Year,Month,Total Flights,Distance,Points Accumulated,Points Redeemed,Dollar Cost Points Redeemed
0,100590,2018,6,12,15276,22914.0,0,0
1,100590,2018,7,12,9168,13752.0,0,0
2,100590,2018,5,4,6504,9756.0,0,0
11,102376,2018,6,24,21216,31824.0,0,0
12,102376,2018,12,15,16500,24750.0,556,100
...,...,...,...,...,...,...,...,...
392926,999986,2018,8,8,14680,22020.0,655,118
392927,999986,2018,11,6,4338,6507.0,0,0
392928,999986,2018,10,4,4588,6882.0,0,0
392929,999986,2018,2,1,1786,2679.0,544,98
392930,999986,2018,3,1,1069,1603.5,0,0

In [16]:
activity['Points Redeemed'].value_counts()

Points Redeemed
0      157877
443        89
516        88
447        87
457        85
        ...
834         1
859         1
862         1
869         1
858         1
Name: count, Length: 586, dtype: int64

In [17]:
activity.drop(["Points Redeemed","Dollar Cost Points Redeemed"] ,axis=1 , inplace=True)

C:\Users\AbTech\AppData\Local\Temp\ipykernel_1284\2030302280.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  activity.drop(["Points Redeemed","Dollar Cost Points Redeemed"] ,axis=1 , inplace=True)

C:\Users\AbTech\AppData\Local\Temp\ipykernel_8948\2692564336.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  activity['Month'] = pd.to_datetime(activity['Month'], format='%m').dt.strftime('%b')

In [18]:
activity

,Loyalty Number,Year,Month,Total Flights,Distance,Points Accumulated
0,100590,2018,6,12,15276,22914.0
1,100590,2018,7,12,9168,13752.0
2,100590,2018,5,4,6504,9756.0
11,102376,2018,6,24,21216,31824.0
12,102376,2018,12,15,16500,24750.0
...,...,...,...,...,...,...
392926,999986,2018,8,8,14680,22020.0
392927,999986,2018,11,6,4338,6507.0
392928,999986,2018,10,4,4588,6882.0
392929,999986,2018,2,1,1786,2679.0
392930,999986,2018,3,1,1069,1603.5

C:\Users\AbTech\AppData\Local\Temp\ipykernel_8948\1549574974.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  activity['Year'] = pd.to_datetime(activity['Year'], format='%Y').dt.strftime('%b')

In [21]:
activity.to_csv("Customer Flight Activity.csv", index=False)

In [22]:
activity

,Loyalty Number,Year,Month,Total Flights,Distance,Points Accumulated
0,100590,2018,6,12,15276,22914.0
1,100590,2018,7,12,9168,13752.0
2,100590,2018,5,4,6504,9756.0
11,102376,2018,6,24,21216,31824.0
12,102376,2018,12,15,16500,24750.0
...,...,...,...,...,...,...
392926,999986,2018,8,8,14680,22020.0
392927,999986,2018,11,6,4338,6507.0
392928,999986,2018,10,4,4588,6882.0
392929,999986,2018,2,1,1786,2679.0
392930,999986,2018,3,1,1069,1603.5

In [23]:
loyality = pd.read_csv("G:\\data analysis\\final project\\Customer Loyalty History.csv")
loyality

,Loyalty Number,Country,Province,City,Postal Code,Gender,Education,Salary,Marital Status,Loyalty Card,CLV,Enrollment Type,Enrollment Year,Enrollment Month,Cancellation Year,Cancellation Month
0,480934,Canada,Ontario,Toronto,M2Z 4K1,Female,Bachelor,83236.0,Married,Star,3839.14,Standard,2016,2,NaN,NaN
1,549612,Canada,Alberta,Edmonton,T3G 6Y6,Male,College,NaN,Divorced,Star,3839.61,Standard,2016,3,NaN,NaN
2,429460,Canada,British Columbia,Vancouver,V6E 3D9,Male,College,NaN,Single,Star,3839.75,Standard,2014,7,2018.0,1.0
3,608370,Canada,Ontario,Toronto,P1W 1K4,Male,College,NaN,Single,Star,3839.75,Standard,2013,2,NaN,NaN
4,530508,Canada,Quebec,Hull,J8Y 3Z5,Male,Bachelor,103495.0,Married,Star,3842.79,Standard,2014,10,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16732,823768,Canada,British Columbia,Vancouver,V6E 3Z3,Female,College,NaN,Married,Star,61850.19,Standard,2012,12,NaN,NaN
16733,680886,Canada,Saskatchewan,Regina,S1J 3C5,Female,Bachelor,89210.0,Married,Star,67907.27,Standard,2014,9,NaN,NaN
16734,776187,Canada,British Columbia,Vancouver,V5R 1W3,Male,College,NaN,Single,Star,74228.52,Standard,2014,3,NaN,NaN
16735,906428,Canada,Yukon,Whitehorse,Y2K 6R0,Male,Bachelor,-57297.0,Married,Star,10018.66,2018 Promotion,2018,4,NaN,NaN
16736,652627,Canada,Manitoba,Winnipeg,R2C 0M5,Female,Bachelor,75049.0,Married,Star,83325.38,Standard,2015,12,2016.0,8.0

In [24]:
loyality.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16737 entries, 0 to 16736
Data columns (total 16 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Loyalty Number      16737 non-null  int64
 1   Country             16737 non-null  object
 2   Province            16737 non-null  object
 3   City                16737 non-null  object
 4   Postal Code         16737 non-null  object
 5   Gender              16737 non-null  object
 6   Education           16737 non-null  object
 7   Salary              12499 non-null  float64
 8   Marital Status      16737 non-null  object
 9   Loyalty Card        16737 non-null  object
 10  CLV                 16737 non-null  float64
 11  Enrollment Type     16737 non-null  object
 12  Enrollment Year     16737 non-null  int64
 13  Enrollment Month    16737 non-null  int64
 14  Cancellation Year   2067 non-null   float64
 15  Cancellation Month  2067 non-null   float64
dtypes: float64(4), int64(3), object(9)
memory usage: 2.0+ MB

In [25]:
loyality.isnull().sum()

Loyalty Number            0
Country                   0
Province                  0
City                      0
Postal Code               0
Gender                    0
Education                 0
Salary                 4238
Marital Status            0
Loyalty Card              0
CLV                       0
Enrollment Type           0
Enrollment Year           0
Enrollment Month          0
Cancellation Year     14670
Cancellation Month    14670
dtype: int64

In [26]:
loyality.describe()

,Loyalty Number,Salary,CLV,Enrollment Year,Enrollment Month,Cancellation Year,Cancellation Month
count,16737.000000,12499.000000,16737.000000,16737.000000,16737.000000,2067.000000,2067.000000
mean,549735.880445,79245.609409,7988.896536,2015.253211,6.669116,2016.503145,6.962748
std,258912.132453,35008.297285,6860.982280,1.979111,3.398958,1.380743,3.455297
min,100018.000000,-58486.000000,1898.010000,2012.000000,1.000000,2013.000000,1.000000
25%,326603.000000,59246.500000,3980.840000,2014.000000,4.000000,2016.000000,4.000000
50%,550434.000000,73455.000000,5780.180000,2015.000000,7.000000,2017.000000,7.000000
75%,772019.000000,88517.500000,8940.580000,2017.000000,10.000000,2018.000000,10.000000
max,999986.000000,407228.000000,83325.380000,2018.000000,12.000000,2018.000000,12.000000

In [27]:
(loyality['Salary']< 0).sum()

np.int64(20)

In [29]:
mean_salary = loyality['Salary'].mean()
loyality['Salary']=loyality['Salary'].fillna(mean_salary)

In [30]:
loyality = loyality[loyality['Salary']>=0]

In [31]:
(loyality['Salary']< 0).sum()

np.int64(0)

In [32]:
loyality.isnull().sum()

Loyalty Number            0
Country                   0
Province                  0
City                      0
Postal Code               0
Gender                    0
Education                 0
Salary                    0
Marital Status            0
Loyalty Card              0
CLV                       0
Enrollment Type           0
Enrollment Year           0
Enrollment Month          0
Cancellation Year     14652
Cancellation Month    14652
dtype: int64

In [34]:
loyality.info()

<class 'pandas.core.frame.DataFrame'>
Index: 16717 entries, 0 to 16736
Data columns (total 16 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Loyalty Number      16717 non-null  int64
 1   Country             16717 non-null  object
 2   Province            16717 non-null  object
 3   City                16717 non-null  object
 4   Postal Code         16717 non-null  object
 5   Gender              16717 non-null  object
 6   Education           16717 non-null  object
 7   Salary              16717 non-null  float64
 8   Marital Status      16717 non-null  object
 9   Loyalty Card        16717 non-null  object
 10  CLV                 16717 non-null  float64
 11  Enrollment Type     16717 non-null  object
 12  Enrollment Year     16717 non-null  int64
 13  Enrollment Month    16717 non-null  int64
 14  Cancellation Year   2065 non-null   float64
 15  Cancellation Month  2065 non-null   float64
dtypes: float64(4), int64(3), object(9)
memory usage: 2.2+ MB

In [33]:
loyality

,Loyalty Number,Country,Province,City,Postal Code,Gender,Education,Salary,Marital Status,Loyalty Card,CLV,Enrollment Type,Enrollment Year,Enrollment Month,Cancellation Year,Cancellation Month
0,480934,Canada,Ontario,Toronto,M2Z 4K1,Female,Bachelor,83236.000000,Married,Star,3839.14,Standard,2016,2,NaN,NaN
1,549612,Canada,Alberta,Edmonton,T3G 6Y6,Male,College,79245.609409,Divorced,Star,3839.61,Standard,2016,3,NaN,NaN
2,429460,Canada,British Columbia,Vancouver,V6E 3D9,Male,College,79245.609409,Single,Star,3839.75,Standard,2014,7,2018.0,1.0
3,608370,Canada,Ontario,Toronto,P1W 1K4,Male,College,79245.609409,Single,Star,3839.75,Standard,2013,2,NaN,NaN
4,530508,Canada,Quebec,Hull,J8Y 3Z5,Male,Bachelor,103495.000000,Married,Star,3842.79,Standard,2014,10,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16731,900501,Canada,Ontario,Sudbury,M5V 1G5,Male,College,79245.609409,Single,Star,61134.68,Standard,2012,9,NaN,NaN
16732,823768,Canada,British Columbia,Vancouver,V6E 3Z3,Female,College,79245.609409,Married,Star,61850.19,Standard,2012,12,NaN,NaN
16733,680886,Canada,Saskatchewan,Regina,S1J 3C5,Female,Bachelor,89210.000000,Married,Star,67907.27,Standard,2014,9,NaN,NaN
16734,776187,Canada,British Columbia,Vancouver,V5R 1W3,Male,College,79245.609409,Single,Star,74228.52,Standard,2014,3,NaN,NaN
16736,652627,Canada,Manitoba,Winnipeg,R2C 0M5,Female,Bachelor,75049.000000,Married,Star,83325.38,Standard,2015,12,2016.0,8.0

In [35]:
loyality.drop(['Cancellation Year', 'Cancellation Month'], axis=1, inplace=True)

C:\Users\AbTech\AppData\Local\Temp\ipykernel_1284\4269176133.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  loyality.drop(['Cancellation Year', 'Cancellation Month'], axis=1, inplace=True)

In [36]:
loyality

,Loyalty Number,Country,Province,City,Postal Code,Gender,Education,Salary,Marital Status,Loyalty Card,CLV,Enrollment Type,Enrollment Year,Enrollment Month
0,480934,Canada,Ontario,Toronto,M2Z 4K1,Female,Bachelor,83236.000000,Married,Star,3839.14,Standard,2016,2
1,549612,Canada,Alberta,Edmonton,T3G 6Y6,Male,College,79245.609409,Divorced,Star,3839.61,Standard,2016,3
2,429460,Canada,British Columbia,Vancouver,V6E 3D9,Male,College,79245.609409,Single,Star,3839.75,Standard,2014,7
3,608370,Canada,Ontario,Toronto,P1W 1K4,Male,College,79245.609409,Single,Star,3839.75,Standard,2013,2
4,530508,Canada,Quebec,Hull,J8Y 3Z5,Male,Bachelor,103495.000000,Married,Star,3842.79,Standard,2014,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16731,900501,Canada,Ontario,Sudbury,M5V 1G5,Male,College,79245.609409,Single,Star,61134.68,Standard,2012,9
16732,823768,Canada,British Columbia,Vancouver,V6E 3Z3,Female,College,79245.609409,Married,Star,61850.19,Standard,2012,12
16733,680886,Canada,Saskatchewan,Regina,S1J 3C5,Female,Bachelor,89210.000000,Married,Star,67907.27,Standard,2014,9
16734,776187,Canada,British Columbia,Vancouver,V5R 1W3,Male,College,79245.609409,Single,Star,74228.52,Standard,2014,3
16736,652627,Canada,Manitoba,Winnipeg,R2C 0M5,Female,Bachelor,75049.000000,Married,Star,83325.38,Standard,2015,12

In [37]:
loyality.to_csv("Customer Loyalty History.csv", index=False)

In [38]:
loyality

,Loyalty Number,Country,Province,City,Postal Code,Gender,Education,Salary,Marital Status,Loyalty Card,CLV,Enrollment Type,Enrollment Year,Enrollment Month
0,480934,Canada,Ontario,Toronto,M2Z 4K1,Female,Bachelor,83236.000000,Married,Star,3839.14,Standard,2016,2
1,549612,Canada,Alberta,Edmonton,T3G 6Y6,Male,College,79245.609409,Divorced,Star,3839.61,Standard,2016,3
2,429460,Canada,British Columbia,Vancouver,V6E 3D9,Male,College,79245.609409,Single,Star,3839.75,Standard,2014,7
3,608370,Canada,Ontario,Toronto,P1W 1K4,Male,College,79245.609409,Single,Star,3839.75,Standard,2013,2
4,530508,Canada,Quebec,Hull,J8Y 3Z5,Male,Bachelor,103495.000000,Married,Star,3842.79,Standard,2014,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16731,900501,Canada,Ontario,Sudbury,M5V 1G5,Male,College,79245.609409,Single,Star,61134.68,Standard,2012,9
16732,823768,Canada,British Columbia,Vancouver,V6E 3Z3,Female,College,79245.609409,Married,Star,61850.19,Standard,2012,12
16733,680886,Canada,Saskatchewan,Regina,S1J 3C5,Female,Bachelor,89210.000000,Married,Star,67907.27,Standard,2014,9
16734,776187,Canada,British Columbia,Vancouver,V5R 1W3,Male,College,79245.609409,Single,Star,74228.52,Standard,2014,3
16736,652627,Canada,Manitoba,Winnipeg,R2C 0M5,Female,Bachelor,75049.000000,Married,Star,83325.38,Standard,2015,12

In [40]:
loyality.duplicated().sum()

np.int64(0)